project_dbt:
  outputs:
    dev:
      dataset: dev
      fixed_retries: 1
      keyfile: /workspaces/dagster-canvas-lms/service.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT') }}"
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev
